/**
 * Book outline schema (§3.2).
 *
 * Represents the full structural outline of a book project: parts, chapters,
 * sections with beats, and rich-text front/back matter.
 *
 * @module
 * @version 1.0.0 | 2026-07-16
 */

import { z } from 'zod';

// ── Rich-block (discriminated union on `type`) ────────────────────────────────

export const RichBlockSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('paragraph'), text: z.string() }),
  z.object({ type: z.literal('heading'), level: z.number().min(2).max(4), text: z.string() }),
  z.object({ type: z.literal('list'), ordered: z.boolean(), items: z.array(z.string()) }),
  z.object({ type: z.literal('table'), headers: z.array(z.string()), rows: z.array(z.array(z.string())) }),
]);

export type RichBlock = z.infer<typeof RichBlockSchema>;

// ── Section within a chapter ──────────────────────────────────────────────────

const SectionSchema = z.object({
  id: z.string(), // ULID
  number: z.string(), // e.g. "1.1", "1.2"
  title: z.string(),
  wordTarget: z.number().nullable(),
  beats: z.array(z.string()),
});

// ── Chapter within an outline part ────────────────────────────────────────────

export const OutlineChapterSchema = z.object({
  chapterId: z.string(), // ULID
  title: z.string(),
  wordTarget: z
    .object({
      min: z.number(),
      max: z.number(),
    })
    .nullable(),
  sections: z.array(SectionSchema),
});

export type OutlineChapter = z.infer<typeof OutlineChapterSchema>;

// ── Part grouping ─────────────────────────────────────────────────────────────

const OutlinePartSchema = z.object({
  id: z.string(), // ULID
  title: z.string(),
  chapters: z.array(OutlineChapterSchema),
});

// ── Top-level outline ─────────────────────────────────────────────────────────

export const OutlineSchema = z.object({
  schemaVersion: z.literal(1),
  frontMatter: z.array(RichBlockSchema),
  parts: z.array(OutlinePartSchema),
  backMatter: z.array(RichBlockSchema),
});

export type Outline = z.infer<typeof OutlineSchema>;

// ── Parse preview (used by outline importer and IPC) ─────────────────────────
// These interfaces represent the result of parsing a markdown outline.
// They are plain-data types (no Zod schemas) because they are generated by
// the parser, not validated from external input.

/** A single section within a chapter, as returned by the markdown parser. */
export interface ParsedSection {
  id: string; // ULID
  number: string; // e.g. "1.1", "1.2", or "E" for epilogue
  title: string;
  wordTarget: number | null;
  beats: string[];
}

/** A chapter as returned by the markdown parser. */
export interface ParsedChapter {
  chapterId: string; // ULID
  title: string;
  wordTarget: { min: number; max: number } | null;
  sections: ParsedSection[];
}

/** A part as returned by the markdown parser. */
export interface ParsedPart {
  id: string; // ULID
  title: string;
  chapters: ParsedChapter[];
}

/**
 * Full parse result returned by `parseOutlineMarkdown`.
 *
 * Contains both the human-readable preview breakdown and the serialisable
 * Outline + StructureItem[] that get committed to the book-project repo.
 */
export interface ParsePreview {
  projectTitle: string;
  frontMatter: RichBlock[];
  parts: ParsedPart[];
  backMatter: RichBlock[];
  /** The fully-formed Outline (validated against OutlineSchema). */
  outline: Outline;
  /** Structure items for the project manifest (includes parts + standalone chapters). */
  structure: import('./project').StructureItem[];
}

// ── Outline mutation types ────────────────────────────────────────────────────

/**
 * An atomic mutation applied to an Outline.
 *
 * Each mutation is a discriminated union on the `kind` field.
 * Mutations are applied in order and should be validated before commit.
 */
export type OutlineMutation =
  | { kind: 'renamePart'; partId: string; title: string }
  | { kind: 'renameChapter'; chapterId: string; title: string }
  | { kind: 'renameSection'; sectionId: string; title: string }
  | { kind: 'reorderPart'; partId: string; newIndex: number }
  | { kind: 'reorderChapter'; chapterId: string; targetPartId: string | null; newIndex: number }
  | { kind: 'reorderSection'; sectionId: string; chapterId: string; newIndex: number }
  | { kind: 'deletePart'; partId: string }
  | { kind: 'deleteChapter'; chapterId: string }
  | { kind: 'deleteSection'; sectionId: string }
  | { kind: 'addPart'; part: { id: string; title: string; chapters: [] } }
  | { kind: 'addChapter'; chapter: { chapterId: string; title: string; wordTarget: { min: number; max: number } | null; sections: [] }; partId: string | null }
  | { kind: 'addSection'; section: { id: string; number: string; title: string; wordTarget: number | null; beats: string[] }; chapterId: string }
  | { kind: 'updateBeat'; sectionId: string; beatIndex: number; newText: string }
  | { kind: 'addBeat'; sectionId: string; text: string; atIndex?: number }
  | { kind: 'removeBeat'; sectionId: string; beatIndex: number };
